<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Mini-Shop on Zend Framework</title>

    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/styles.css'); ?>

    <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery-1.11.0.min.js') ?>
    <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery.lazyload.min.js') ?>
    <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/script.js') ?>

</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>Mini-Shop on Zend Framework</b>
    </div>
</div>
<div class="head-menu">
    <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
        <?php $urlLogout = $this->url(array('controller'=>'auth', 'action' => 'logout')); ?>
        <?php $urlContact = $this->url(array('controller'=>'auth', 'action' => 'contact-us')); ?>
        <?php $urlUseredit = $this->url(array('controller'=>'user', 'action' => 'index')); ?>
        <?php $urlCart = $this->url(array('controller'=>'cart', 'action' => 'view')) ?>
        <div class="link-home">
            <a href="/">Home</a>
        </div>
        <div class="link-contact-us">
            <a href = "<?php echo $urlUseredit; ?>">My Profile</a>
        </div>
        <div class="link-contact-us">
            <a href = "<?php echo $urlContact; ?>">Contact Us</a>
        </div>
        <div class="link-cart">
            <a href="<?php echo $urlCart; ?>">Cart</a>
        </div>
        <div class="link-logout">
            <a href = "<?php echo $urlLogout; ?>">Logout</a>
        </div>
    <?php endif; ?>
</div>
<?php echo $this->layout()->content ?>

</body>
</html>